---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      node-feature-discovery:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/kubernetes-sigs/node-feature-discovery
              tag: v0.17.3
          master:
            replicaCount: 1
          worker:
            config:
              core:
                labelSources: ["pci", "system", "usb"]
          prometheus:
            enable: true
