---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      node-red:
        annotations:
          reloader.stakater.com/auto: 'true'

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: 'OnRootMismatch'

        containers:
          app:
            image:
              repository: docker.io/nodered/node-red
              tag: 4.0.2
            envFrom:
              - secretRef:
                  name: node-red-secret
            resources:
              requests:
                cpu: 5m
                memory: 512Mi
              limits:
                memory: 512Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: node-red
        ports:
          http:
            port: 1880

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
        hosts:
          - host: &host nr.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]

    persistence:
      data:
        existingClaim: *app

      settings:
        type: configMap
        name: node-red-configmap
        globalMounts:
          - path: /data/settings.js
            subPath: settings.js
            readOnly: true

      tmp:
        type: emptyDir
