---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    template:
      data:

        # CROSS SEED

        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"

        # PROTONVPN

        WIREGUARD_ENDPOINT_IP: "{{ .WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"

        # PUSHOVER
        PUSHOVER_TOKEN: "{{ .QBITTORRENT_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"

  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: protonvpn
    - extract:
        key: pushover
    - extract:
        key: qbittorrent

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun-secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: gluetun
