---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      qbittorrent:
        type: statefulset

        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-secret,qbittorrent-gluetun-secret

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          terminationGracePeriodSeconds: 120

        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.8@sha256:025f8f5e2b20542c0e26d42771a60234cbdf3417e7bddcf6622c5dc3f3f49de2
            restartPolicy: Always
          gluetun:
            dependsOn:
              - dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            restartPolicy: Always
            env:
              DOT: "off"
              DNS_ADDRESS: 127.0.0.2
              HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: &gluetunAuthPath /gluetun/auth.toml
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: &port 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            lifecycle:
              postStart:
                exec:
                  command:
                    - "/bin/sh"
                    - "-c"
                    - "(ip rule del table 51820; ip -6 rule del table 51820) || true"
            securityContext:
              capabilities: { add: ["NET_ADMIN"] }
              allowPrivilegeEscalation: false
            resources:
              limits:
                squat.ai/tun: "1"

        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.0.4
            env:
              UMASK: "022"
              XSEED_HOST: cross-seed.default.svc.cluster.local
              XSEED_PORT: 80
              XSEED_APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: CROSS_SEED_API_KEY
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 2048Mi
              limits:
                memory: 5Gi

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4@sha256:5fd1da9f2d6509c00b6d6f4b3b7ada6fa097b8134040fc8965b6c1dc8584dc6b
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              GLUETUN_CONTROL_SERVER_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: GLUETUN_CONTROL_SERVER_API_KEY
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: qb.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          qbittorrent:
            app:
              - path: /config

      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config

      downloads:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media
        globalMounts:
          - path: /media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent

      gluetun-auth:
        type: secret
        name: qbittorrent-gluetun-secret
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: *gluetunAuthPath
                subPath: auth.toml

      dnsdist:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          qbittorrent:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true

      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          qbittorrent:
            app:
              - path: /config/scripts
