---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizationresources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml

configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - scripts/post-process.sh
  - name: qbittorrent-coredns
    files:
      - ./config/Corefile
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
