---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml

configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - ./resources/post-process.sh

  - name: qbittorrent-dnsdist
    files:
      - ./resources/dnsdist.conf

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
