---
bootstrap_cluster_name: "main"

# (Required) Generated schematic id from https://factory.talos.dev/
bootstrap_schematic_id: "f0bab41395003b80e28f0d80c8fff4b264243942ad9b29ba2280d529eb2045df"

# (Required) The CIDR your nodes are on (e.g. 192.168.1.0/24)
bootstrap_node_network: "10.1.33.0/24"
bootstrap_node_inventory:
    - name: "kube-01"
      controller: true
      disk: "/dev/nvme0n1"
      mac_addr: "10:62:e5:00:4c:12"
      mtu: "1500"
    - name: "kube-02"
      controller: true
      disk: "/dev/nvme0n1"
      mac_addr: "18:60:24:27:27:a7"
      mtu: "1500"
    - name: "kube-03"
      controller: true
      disk: "/dev/nvme0n1"
      mac_addr: "ac:e2:d3:0d:60:f0"
      mtu: "1500"
    - name: "kube-04"  
      controller: false
      disk: "/dev/nvme0n1"
      mac_addr: "ac:e2:d3:10:d8:25"
      mtu: "1500"
    - name: "kube-05"
      controller: false
      disk: "/dev/nvme0n1"
      mac_addr: "ac:e2:d3:15:fd:f9"
      mtu: "1500"

bootstrap_dns_servers: []
  
# (Optional) The NTP servers to use for the cluster nodes.
#   Default is pulled from your DHCP server.
bootstrap_ntp_servers: []

# (Required) The pod CIDR for the cluster, this must NOT overlap with any
#   existing networks and is usually a /16 (64K IPs).
# If you want to use IPv6 check the advanced flags below and be aware of
# https://github.com/onedr0p/cluster-template/issues/1148
bootstrap_pod_network: "10.69.0.0/16"

# (Required) The service CIDR for the cluster, this must NOT overlap with any
#   existing networks and is usually a /16 (64K IPs).
# If you want to use IPv6 check the advanced flags below and be aware of
# https://github.com/onedr0p/cluster-template/issues/1148
bootstrap_service_network: "10.96.0.0/16"

# (Required) The IP address of the Kube API, choose an available IP in
#   your nodes host network that is NOT being used. This is announced over L2.
bootstrap_controller_vip: "10.1.33.254"

# (Optional) Add additional SANs to the Kube API cert, this is useful
#   if you want to call the Kube API by hostname rather than IP
bootstrap_tls_sans: "kubecluster.robsonhome.cloud"

# (Optional) The default gateway for the nodes
#   Default is .1 which is derrived from bootstrap_node_network (e.g. 192.168.1.1)
bootstrap_node_default_gateway: "10.1.33.1"

# (Optional) Add vlan tag to network master device, this is not needed if you tag ports on your switch with the VLAN
#   See: https://www.talos.dev/latest/advanced/advanced-networking/#vlans
bootstrap_vlan: ""

# (Required) Age Public Key (e.g. age1...)
# 1. Generate a new key with the following command:
#    > task sops:age-keygen
# 2. Copy the PUBLIC key and paste it below
bootstrap_sops_age_pubkey: "age16y6722khkktjs32yl9a7l4mwettdjm9klxjskahq0wt3h0vd6ycs0hjztv"

# (Optional) Use cilium BGP control plane when L2 announcements won't traverse VLAN network segments.
#   Needs a BGP capable router setup with the node IPs as peers.
#   See: https://docs.cilium.io/en/latest/network/bgp-control-plane/
bootstrap_bgp:
  enabled: false
  # (Optional) If using multiple BGP peers add them here.
  #   Default is .1 derrived from host_network: ['x.x.x.1']
  # peers: "10.1.33.1"
  # (Required) Set the BGP Autonomous System Number for the router(s) and nodes.
  #   If these match, iBGP will be used. If not, eBGP will be used.
  # peer_asn: "65401"   # Router(s) AS
  # local_asn: "65401"  # Node(s) AS
  # peer_port: 179 # BGP Port - default is TCP port 179
  # (Required) The advertised CIDR for the cluster, this must NOT overlap with any
  #   existing networks and is usually a /16 (64K IPs).
  # If you want to use IPv6 check the advanced flags below
  # advertised_network: "10.45.0.1/16"

# (Optional) Secureboot and TPM-based disk encryption
bootstrap_secureboot:
  # (Optional) Enable secureboot on UEFI systems. Not supported on x86 platforms in BIOS mode.
  #   See: https://www.talos.dev/latest/talos-guides/install/bare-metal-platforms/secureboot
  enabled: false
  # (Optional) Enable TPM-based disk encryption. Requires TPM 2.0
  #   See: https://www.talos.dev/v1.6/talos-guides/install/bare-metal-platforms/secureboot/#disk-encryption-with-tpm
  encrypt_disk_with_tpm: false

#
# 2. (Required) Flux details - Flux is used to manage the cluster configuration.
#

# (Required) GitHub repository URL
#   For a public repo use the 'https://' URL (e.g. "https://github.com/onedr0p/cluster-template.git")
#   For a private repo use the 'ssh://' URL (e.g. "ssh://git@github.com/onedr0p/cluster-template.git")
#     If using a private repo make sure to following the instructions with the 'bootstrap_github_private_key' option below.
bootstrap_github_address: "https://github.com/DylansDecoded/home-ops.git"
bootstrap_github_branch: "main"
bootstrap_github_webhook_token: "bde489855f5259418be722741301d1e038f1b2c4"
bootstrap_github_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAyTtIHj1sKH9Gd3y7Qu2VuqN++473B2DWje5+G5vfmq4FrPAF
  9cAB76g15YrxUrIZNC6SX3N0kusOWPSm9C7nzxpLH+577Clu+uyhZkFbtGPGEdtY
  q4nOteL9eDDHJprePhNKf3/oMl3A97dMzWpfBK0hLcBRLjW7jVUCWCMZEcKW0DdV
  rjtClbikuNtIAeZcGIwbtijFmPdmuZ8YcvYBUM+1Xhl9j9YgENAViMicJo5zipHF
  TpYtwIzNaNJXnKbojDlr6wJ3/b8s7Q8oHdujpnSVtg/ieOr4rsFW8igBtcMfj/0G
  3NXvqlrW2cA9iA3dkS1iyZAI7ZznowH+TmqMMQIDAQABAoIBAHTXhA9y8KsvA5Z7
  iSvaUdcV+bRNFahmFQ5CTVzwi8v/gXIhyAQiYb1q+Sh4HZk7qiC/beQYYLax3xnN
  rGcaGSUKilZXHgNJJ5Rw82IxTvMV/7r8lqa7lJfN3gj8oZYL1EFM6DPR69vaziHH
  f8PCILvRXvN2uGxRbL4qfvr4HiVNxJQS0mhHEe9rbqnNh0+zSjz4SW26RY436uVL
  iiwjHSf4vnLk1ZgqEpMFURRMt4Xv+H/uu66o79SMBPqy2yLPjGgIY2pgv7xj3ioA
  RHGr4RArwIDyxlAxMbdUFqAO6W7CEzLKNnasR9/uZ1+t6fmAgVeL0Q3Y5p9bOIeX
  Zv+QVTECgYEA6roLybRGbl+69yybyN7etn47eV5IihZ9+OKk4xuweY1YwWHeUDvV
  KvYeopaatw0PClKRF/Q5C8S3mULpX+WTwJcBUyaY/SJIDm0Q2d+/Ixy4WjcVUame
  a9JqSTOQS54ixGO6zqPMARASk1xiaoW0om+UPaOgCUAtZTO0Hl1eU5UCgYEA23gb
  EyFgRZJv7E6FtdmHQPVQVCgZeXkWGqWFWWizVX0YmrbegMaKfReuE+/K2r3cEnST
  OxBzpyn6PB2D6KsFdtjNwLaNZ13tRsjt+aADjT7wzY7R79CudJ/4Gkbai5je9Jfv
  hGs1CbTHpWFik3/JGKHqrYlGhHZb4uM7c3Ynry0CgYEAq3GQQpdGCkAp03floWYH
  zcuNrSxMV2/uOudv/+GtmFrBRR4yvu+011hFMARIpQMIxUVhbNmZARuB7pOM2dpZ
  fQXOlelPPTTY5JCNClX+yaqkjGBHVgpKB/78WtMqxdCPHFqri1rgGraemruTtrJK
  KYrN/+ePcLJLdeu516PizbECgYB8zWv4EP7CEWf8JRr8MlsroVSwxqzV2vmq5X1T
  PqrcbmrTcDJPYJfYUuL3C2F7yoOfKxOeftiFsuVN0ir04GwXDWrTr/vxUARiQFiz
  nz7lz2j4O8M+cJkEUQOxTaFxyNjglpXp410hy9/MN/jqj7w3ebwOOwYSxYuzFiz0
  l7gxcQKBgEuEvMyMUU5PqLxNLlLhv8Kqrv95uzTECS7vNyFy7Jes4oZg/M+1X4aT
  QKW0sh92cE+tuT4SMMenrGdhJdnfAB5b/pEj6u+hkd4BleGwqpo6Lp9afjA8AnYl
  ge8GoML5qGNrOhDr5q2AgAEmnjxFx09oPxy6ZfxdXbdYKanNcUNv
  -----END RSA PRIVATE KEY-----

bootstrap_cloudflare:
  enabled: true
  domain: "robsonhome.cloud"
  token: "1gTdJzmQY7u2L9WD-oYWGmEHZALtExqoezyBnoXw"
  acme:
    email: "admin@robsonhome.cloud"
    production: true
  ingress_vip: "10.1.33."
  gateway_vip: "10.45.0.4"
  tunnel:
    id: "e901488f-a148-4024-b5a7-8537e7b42287"
    account_id: "5a8862340df663c8595cce75ffa77854"
    secret: "QZI0ylpQ+upHisShDbpbB+k++J+Wly0XStbQw8Ki7wI="
    ingress_vip: "10.45.0.3"
