apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-01-13T05:50:46Z"
  generateName: sabnzbd-6b68b5c4f-
  labels:
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
    pod-template-hash: 6b68b5c4f
  name: sabnzbd-6b68b5c4f-8pmcv
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: sabnzbd-6b68b5c4f
    uid: eff89106-01e0-4b6e-8706-c42ac5a796e5
  resourceVersion: "2452787"
  uid: d502b25c-65e3-449d-8086-1c37d7060d51
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    - name: CROSS_SEED_ENABLED
      value: "false"
    - name: CROSS_SEED_HOST
      value: cross-seed.default.svc.cluster.local
    - name: CROSS_SEED_PORT
      value: "80"
    - name: CROSS_SEED_SLEEP_INTERVAL
      value: "30"
    - name: PUSHOVER_ENABLED
      value: "true"
    - name: SABNZBD__HOST_WHITELIST_ENTRIES
      value: sabnzbd, sabnzbd.default, sabnzbd.default.svc, sabnzbd.default.svc.cluster,
        sabnzbd.default.svc.cluster.local, sab.robsonhome.cloud
    - name: SABNZBD__PORT
      value: "80"
    - name: TZ
      value: America/New_York
    envFrom:
    - secretRef:
        name: sabnzbd-secret
    image: ghcr.io/onedr0p/sabnzbd:4.4.1@sha256:4188d3c29c53de1018edcfd5dc2d0a0c7955b9a239b91ff6c859626abd3494dc
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /api?mode=version
        port: 80
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: app
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api?mode=version
        port: 80
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 12Gi
        cpu: 250m
      requests:
        cpu: 100m
        memory: 12Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /media/downloads/usenet
      name: media
      subPath: downloads/usenet
    - mountPath: /scripts
      name: scripts
      readOnly: true
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lmbvs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: k8s-3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: sabnzbd
  - name: media
    nfs:
      path: /mnt/tank/media
      server: truenas.robsonhome.cloud
  - configMap:
      defaultMode: 509
      name: sabnzbd-scripts
    name: scripts
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-lmbvs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-13T05:50:46Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-01-13T05:50:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-13T05:50:46Z"
    message: 'containers with unready status: [app]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-13T05:50:46Z"
    message: 'containers with unready status: [app]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-13T05:50:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ghcr.io/onedr0p/sabnzbd:4.4.1@sha256:4188d3c29c53de1018edcfd5dc2d0a0c7955b9a239b91ff6c859626abd3494dc
    imageID: ""
    lastState: {}
    name: app
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /media/downloads/usenet
      name: media
    - mountPath: /scripts
      name: scripts
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lmbvs
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.1.20.13
  hostIPs:
  - ip: 10.1.20.13
  phase: Pending
  qosClass: Burstable
  startTime: "2025-01-13T05:50:46Z"
