
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: sample-podxwx
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "multus-services",
        "namespace": "network",
        "mac": "c6:5e:a4:8e:7a:59",
        "ips": ["10.1.30.210/24"],
        "gateway": [ "10.1.30.1" ]
      }]
spec:
  containers:
  - name: sample-pod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF
