
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "multus-services",
              "namespace": "network",
              "ips": [ "10.1.30.90/24" ],
              "mac": "c2:b0:57:49:47:f1",
              "gateway": [ "10.1.30.1" ]
            }]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:3.16
    ports:
    - containerPort: 80
EOF
