---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        # Deploy key
        GH_DEPLOY_KEY: "{{ .HASS_GH_DEPLOY_KEY }}"

        # Home-Assistant
        SECRET_INTERNAL_URL: http://10.1.40.220:8123
        SECRET_INTERNAL_URL_DIRECT: http://10.1.40.220:8123
        SECRET_EXTERNAL_URL: https://hass.robsonhome.cloud
        SECRET_TRUSTED_PROXIES_1: 10.42.0.0/16

        # Home-Assistant Zones
        SECRET_ZONE_HOME_NUMBER: "{{ .HASS_HOME_ADDRESS_NUMBER }}"
        SECRET_ZONE_HOME_POSTAL_CODE: "{{ .HASS_POSTAL_CODE }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .HASS_ELEVATION }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .HASS_LATITUDE }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        
        # Pirate Weather API Key
        SECRET_PIRATE_WEATHER_API_KEY: "{{ .HASS_PIRATE_WEATHER_API_KEY }}"
        
  dataFrom:
    - extract:
        key: home-assistant
