---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.7.4@sha256:3db687091769f145839c0a690143c1a63dbb646fd69711684103b575f070b598
            env:
              TZ: America/New_York
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.42.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1
            env:
              TZ: America/New_York
            args:
              [
                '--auth',
                'none',
                '--user-data-dir',
                '/config/.vscode',
                '--extensions-dir',
                '/config/.vscode',
                '--port',
                '80',
                '/config',
              ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
        hosts:
          - host: hass.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      code:
        className: internal
        hosts:
          - host: hass-code.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: code

    persistence:
      config:
        existingClaim: home-assistant

      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
