# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Pre Flux-Kustomizations
- ./namespace.yaml
# Flux-Kustomizations
- ./autobrr/ks.yaml
- ./cross-seed/ks.yaml
- ./echo-server/ks.yaml
- ./filebrowser/ks.yaml
# - ./frigate/ks.yaml
- ./home-assistant/ks.yaml
- ./kopia/ks.yaml
- ./miniflux/ks.yaml
- ./minio/ks.yaml
- ./omegabrr/ks.yaml
- ./overseerr/ks.yaml
- ./plex/ks.yaml
- ./prowlarr/ks.yaml
- ./qbittorrent/ks.yaml
- ./radarr/ks.yaml
- ./recyclarr/ks.yaml
- ./ring-mqtt/ks.yaml
- ./sabnzbd/ks.yaml
# - ./scrypted/ks.yaml
- ./sonarr/ks.yaml
- ./unpackerr/ks.yaml
- ./zigbee2mqtt/ks.yaml
- ./zwave/ks.yaml
