---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "name": "macvlan-conf",
          "capabilities": { "ips": true },
          "master": "eth0.40",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "10.1.40.0/24",
                "gw": "10.1.40.1"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }