---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-clearnet
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-clearnet",
      "plugins": [
        {
          "type": "host-device",
          "device": "eno1.40",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "dhcp",

            # "routes": [
            #   { "dst": "10.1.40.0/24", "gw": "10.1.40.1" }
            # ]
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }