---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.30",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.1.1.0/24", "gw": "10.1.30.1" },
              { "dst": "10.1.30.0/24", "gw": "10.1.30.1" }
            ]
          }
        }
      ]
    }
