---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-homenet
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-homenet",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.40",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "", "gw": "${NET_IOT_GATEWAY_IP}" },
              { "dst": "${NET_IOT_CIDR}", "gw": "${NET_IOT_GATEWAY_IP}" }
            ]
          }
        }
      ]
    }