---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-services
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-services",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.30",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.1.0.0/16", "gw": "10.1.30.1" }
            ]
          }
        }
      ]
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-services
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-services",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.30",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [{
              "dst": "10.1.0.0/16",
              "gw": "10.1.30.1"
            }]
          }
        }
      ]
    }
