# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: qbtools-secret
stringData:
  config.yaml: ENC[AES256_GCM,data:DczmzTjJrZAg4kH72jOhEzWjT6ZHJ4VpqPzpgNvHU7tp0Uhm17EdiYdg4QNIZDQJXVuCsE9Ao2rATHWFVCaj6ET9G+lJktAHujAwBp+9R6aQqO9SjJNVKCs08+5t8kGqgsBmZVCVK553jQH/N+p4wLfgSQGosIUD5T44E8GunieKDCcgnnftOrq1h/AqbMBdh4ZeCJuUHhS126cBUyTHFF3JjlQZUAnPWKqNnqTN0Fa7Eli8lMXhf/EA04A0dRyzAQYVS7Q14tSQ1vqzmZrcvIpbXoCiBYlGNE0nkef3m+zN8vDNEafZ4h/zA/Z1p/8M6kGbww17fp9uUbTzk1HuDQN9Ch1KKjHZbFY1z4OCWdE82axiLACTI39WxATvNGvc3iJ6JseT3bQI53rbg6aKkq0MUp+MZgvJuiN1uSTYq+yLt6tCE0pOjoT9twm1TJyULEitIdNMegz7bx5ft2KMku99dAvaBdqWHuSlJMi999dAiRM/Dqsn2XgWORK1Hgbcn0ljAg42MstPufLAeEwoUYPMEV4vdx5d+T45h8VqKuRFP90NHGSJW9fLDqUmIDubz+x5AAYYEVq3jPFbQsG7yDImW+tjIw6Qv0+h0gjYHful1j8dIAjD5Jy3eABUFhgDU1OzK4LWHm/eVa8zfzzLBlCbcVjCDUhJzuQp4rLdwE80D8reM/C4SM5V2e+aAB+85kEeQtu6wk83EcyrAcsBr6EVKUh2rnxOZqiNcmbSAOzOMOAywSyiXQHZT5NlQ/Uzthgm45/eZfuDQ2dyRNJA24uISYlduCBMUZacMCAmB4f80bWZuDyVPMbmEa3prKJGbDmmXJB94cz1WSohjt3EKxFzTBL6qQObJcv/vcjMeoF7BMhywi3gkUUW4c7ynXwqoSxPq5rHGs3EQfAyPT7XiEgXKV70HNLk/DIzlfXtq7ShE/ppoB+WyN8lWZCf9uqCD1aWbMEc1nLD1VVbcNU0phyfZbIY/cepaH7qepZkl1KQSH3QEg1NV0d1LpGaz8z2Goa0yllMr8bXi4F6mxc1ri2rFQTRhhWIz+10LvaewjmhbDhs51pQbHoLgqTuph65TuLoGjC+5wzztaeNJk38x3r4fJ8La1//bB/d7RUzXB+9YyY0C/gdd0n6tef0NQCDKT87t5yppUF357Si646VgO6Mkw4M/AllLnBujX49yAGqrTLqLf2STbId2hpqLq7OAC+wgKfDydwL3Zt7kA2kAD2KdrSPFZN3JClcQJShBWVg4ASRflbH513ZRjYiGvS64vzNx7U/Je+/9z40xNdp6Ilro2ZKX3eiBTtAgP2IYAu5Ys6sQZ6zk84bCDzz3/bZ6MNNdAN6tC5S/FdXTzyDqx9I0RYPvm4qF6DhDjnt8QhUiF+zUnn7HQbuE+tt10Bq0CSRMJ6aCZepxEi5ITCe1ulPYnuzR6ew5SqcYsHWxwQ14AelbB/G0JyaqC7O5ZalhN0paMEZuRi/ei+yi1wlfmUhgTPeUxS3Y2Hurfg5oRDmVUMptM2FHDiCfduFSzgF4WUeYusGTcH8TyyAnvM/UyC5loVk+Bs+X2keuNjarP6x3B5yrik5uDPTDZTJl/DSe9m4u7KKjyIhEgg4hjAWPt/OS8i8t8Ql0iMNhzuCeWd+12e/w/LIQQMUKDaKkMCLZ3gwRnN/f4fq+WHogt2N7TKTr7fk,iv:7jGJOKJ3jkDpGWUnfUby0u+F66KZnZ16kN5IwmTelJ0=,tag:kEVag+NIzk5bxZX4g+Ddkg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jwm8ccjgfy04r9rwh65rehk72j6rkawkpjnf4rcu4ukwlcfyquhq4p2q23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcDN1Y1pYdVIxU0VLc3JG
        NHNJWW1SQnIxdnE3K1dsdjZmT0FrVUkxSFE0CnhLUGliUmNWcm96MzVwMTlLT3dV
        di9waVYyS0tLaU0xOHJJOEUxdEt1dDgKLS0tIGZNRi9ML0E5dHhvQzhGV2hJWStm
        NEN3MEtob2RGL0RYV216VVMwWXluZHcK3MRwZ1KQQd7hJ6MEhueMzYpIV8/VQhgw
        bkYlEttd5oxmfnVomeqoakrsgPdnqhdvJBFwRme2MdFptab3kU23hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-14T03:58:36Z"
  mac: ENC[AES256_GCM,data:z2ZxbeKG0TPQ+Qqo/ZI7i9e/I596GGFYdLvAe7+h2LlyrAyOO31Oe62R0bv/n2BoeBOknwh6L2cfzoi+PZUbTPh/sm0JYhPlbRTBGAJdwpBjT94Mboi0VkD29puxUyBNw01hlrfNA6YKWts5+gpTtr76ebOFTpamq0+qAeo7aZE=,iv:f1r9bqhB22RcT2t6GqUy3ZwEQ7iwiPeikTv9rFS7du0=,tag:qpxxSPqhcbtAzPuNVggB8Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.0
