---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizationresources:
  - ./cluster.yaml
  - ./gatus.yaml
  - ./ingress.yaml
  # - ./podmonitor.yaml
