---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-device
spec:
  rules:
    - # Intel UHD Graphics 630
      name: intel.gpu
      labels:
        intel.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0300"] }      # Display controller class
            vendor: { op: In, value: ["8086"] }     # Intel vendor ID
            device: { op: In, value: ["1912"] }     # HD Graphics 530 device ID
