---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${job}
  namespace: ${ns}
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${app}-volsync-secret
    destinationPVC: ${claim}
    copyMethod: Direct
    storageClassName: ceph-block
    # storageClassName: ceph-filesystem
    # accessModes: ["ReadWriteMany"]
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: ${previous}
    moverSecurityContext:
      runAsUser: ${puid}
      runAsGroup: ${pgid}
      fsGroup: ${pgid}
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true

# ---
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationDestination
# metadata:
#   name: {{ ENV.APP }}-manual
#   namespace: {{ ENV.NS }}
# spec:
#   trigger:
#     manual: restore-once
#   restic:
#     repository: {{ ENV.APP }}-volsync-secret
#     destinationPVC: {{ ENV.CLAIM }}
#     copyMethod: Direct
#     storageClassName: {{ ENV.STORAGE_CLASS_NAME }}
#     accessModes: {{ ENV.ACCESS_MODES }}
#     previous: {{ ENV.PREVIOUS }}
#     moverSecurityContext:
#       runAsUser: {{ ENV.PUID }}
#       runAsGroup: {{ ENV.PGID }}
#       fsGroup: {{ ENV.PGID }}
#     enableFileDeletion: true
#     cleanupCachePVC: true
#     cleanupTempPVC: true
