---
apiVersion: batch/v1
kind: Job
metadata:
  name: volsync-unlock-{{ ENV.APP }}
  namespace: ${ns}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: minio
          image: docker.io/restic/restic:latest
          args: ["unlock", "--remove-all"]
          envFrom:
            - secretRef:
                name: ${app}-volsync-secret
          volumeMounts:
            - name: repository
              mountPath: /repository
          resources: {}
        - name: r2
          image: docker.io/restic/restic:latest
          args: ["unlock", "--remove-all"]
          envFrom:
            - secretRef:
                name: ${app}-volsync-r2-secret
          resources: {}
      volumes:
        - name: repository
          nfs:
            server: truenas.robsonhome.cloud
            path: /mnt/tank/apps/volsync
