---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meshcentral
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      meshcentral:
        annotations:
         reloader.stakater.com/auto: "true"
    containers:
      app:
        image: 
          repository: ghcr.io/ylianst/meshcentral
          tag: 1.1.32
      defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: meshcentral
        ports:
          http:
            port: 8086

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.robsonhome.cloud
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.robsonhome.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: meshcentral
        globalMounts:
            - path: /meshcentral/data
              subPath: meshcentral/data

      config-file:
        type: configMap
        name: meshcentral-config
        globalMounts:
          - path: /meshcentral/data/config.json
            subPath: config.json
            readOnly: true

      user_files:
       type: emptyDir
       globalMounts:
        - path: /meshcentral/data/user_files
          subPath: meshcentral/user_files
      
      backups:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/apps/meshcentral
        globalMounts:
          - path: /meshcentral/backups
            subPath: meshcentral/backups
      
      web:
       type: emptyDir
       globalMounts:
         - path: /meshcentral/web
           subPath: meshcentral/web

      
       


