---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${jobName}
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      containers:
        - name: main
          image: docker.io/library/alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache sgdisk util-linux util-linux-misc parted device-mapper;
              sgdisk --zap-all ${ceph_disk};
              dd if=/dev/zero of=${ceph_disk} bs=1M count=100 oflag=direct;
              blkdiscard ${ceph_disk};
              partprobe ${ceph_disk};
          securityContext:
            privileged: true
          resources: {}