---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      emby:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/emby
              tag: 4.8.11
            args:
              - --device=/dev/dri # grant access to the GPU for container user
            env:
              UMASK: 022
              TZ: America/New_York
              PUID: 1000
              PGID: 1000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44]
        seccompProfile: { type: RuntimeDefault }
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
    service:
      app:
        controller: emby
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: external
        hosts:
          - host: "{{ .Release.Name }}.robsonhome.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: emby

      media:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media
        globalMounts:
          - path: /media/media
            subPath: media

      # tv:
      #   type: nfs
      #   server: truenas.robsonhome.cloud
      #   path: /mnt/tank/media/tv
      #   globalMounts:
      #     - path: /media/tv
      #       readOnly: true

      # movies:
      #   type: nfs
      #   server: truenas.robsonhome.cloud
      #   path: /mnt/tank/media/movies
      #   globalMounts:
      #     - path: /media/movies
      #       readOnly: true
