---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      emby:
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: emby/embyserver
              tag: 4.9.1.1
            env:
              TZ: America/New_York
              GIDLIST: 1000,0
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi

    service:
      app:
        ports:
          http:
            port: 8096
    route:
      app:
        hostnames: ["{{ .Release.Name }}.robsonhome.cloud"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: emby

      # cache:
      #   existingClaim: emby-cache
      #   globalMounts:
      #     - path: /config/Cache

      tmp:
        type: emptyDir

      transcode:
        type: emptyDir

      tv:
        type: nfs
        server: 10.1.10.210
        path: /mnt/tank/media/tv
        globalMounts:
          - path: /media/tv
            readOnly: true

      movies:
        type: nfs
        server: 10.1.10.210
        path: /mnt/tank/media/movies
        globalMounts:
          - path: /media/movies
            readOnly: true
