---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      emby:
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: emby/embyserver
              tag: 4.9.1.0
            env:
              TZ: America/New_York
              GIDLIST: 1000,0
            # securityContext:
            #   allowPrivilegeEscalation: true
            #   # readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi

    service:
      app:
        controller: emby
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: external
        hosts:
          - host: "{{ .Release.Name }}.robsonhome.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: emby

      # cache:
      #   existingClaim: emby-cache
      #   globalMounts:
      #     - path: /config/Cache

      tmp:
        type: emptyDir

      transcode:
        type: emptyDir

      tv:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media/tv
        globalMounts:
          - path: /media/tv
            readOnly: true

      movies:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media/movies
        globalMounts:
          - path: /media/movies
            readOnly: true
