---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    template:
      engineVersion: v2
      data:
        REOLINK_CAMERA_PASSWORD: "{{ .REOLINK_PASSWORD }}"
  dataFrom:
    - extract:
        key: reolink
