---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        go2rtc.yaml: |
          api:
            listen: :80
          rtsp:
            listen: :554
          webrtc:
            listen: :8555
            candidates:
              - 10.1.33.123:8555
              - stun:8555
            ice_servers:
              - urls:
                - stun:stun.cloudflare.com:3478
          streams:
            backporch:
              - rtsp://admin:"{{ .REOLINK_PASSWORD }}"@10.1.90.3:554/h264Preview_01_main
            driveway:
              - rtsp://admin:"{{ .REOLINK_PASSWORD }}"@10.1.90.4:554/h264Preview_01_main
  dataFrom:
    - extract:
        key: reolink
