logger:
  default: info

mqtt:
  host: emqx-listeners.default.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

# model:
#   path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr


ffmpeg:
  path: "5.0"
  # Optional: global ffmpeg args (default: shown below)
  global_args: ["-hide_banner", "-loglevel", "warning", "-threads", "2"]
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

  # Optional: global output args
  # output_args:
  #   # Optional: output args for detect streams (default: shown below)
  #   # detect: -threads 2 -f rawvideo -c:v h264_vaapi
  #   # Optional: output args for record streams (default: shown below)
  #   record: preset-record-generic
  # retry_interval: 10

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30


go2rtc:
  streams:
    driveway_floodlight_cam:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main
      - "ffmpeg:driveway_floodlight_cam#video=copy#audio=copy#audio=opus"

    backporch_cam:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main
      - "ffmpeg:backporch_cam#video=copy#audio=copy#audio=opus"


cameras:

  driveway_floodlight_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_cam
          roles:
            - detect
            - record
            - audio

    detect:
      enabled: True
      width: 1536
      height: 576

    motion:
      mask:
        - 0.618,0.279,0.741,0.998,0.94,1,0.87,0.845,0.919,0.641,0.885,0.452,0.788,0.359



    snapshots:
      required_zones:
        - entire_front_yard


    zones:
      entire_front_yard:
        coordinates: 0.091,0.654,0.225,0.415,0.331,0.275,0.416,0.271,0.55,0.277,0.616,0.295,0.738,1,0.158,0.998,0.116,0.82,0.131,0.805
        loitering_time: 5
        objects:
          - person
          - dog
          - cat
      front_yard_street:
        coordinates: 0.394,0.197,0.338,0.268,0.434,0.268,0.614,0.29,0.611,0.208
        objects:
          - car


  backporch_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backporch_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
      min_initialized: 2
      max_disappeared: 25
