logger:
  default: info

mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

# model:
#   path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr


ffmpeg:
  path: "5.0"
  # Optional: global ffmpeg args (default: shown below)
  global_args: ["-hide_banner", "-loglevel", "warning", "-threads", "2"]
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

  # Optional: global output args
  # output_args:
  #   # Optional: output args for detect streams (default: shown below)
  #   # detect: -threads 2 -f rawvideo -c:v h264_vaapi
  #   # Optional: output args for record streams (default: shown below)
  #   record: preset-record-generic
  # retry_interval: 10

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30


go2rtc:
  streams:
    driveway_floodlight_cam:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h265Preview_01_main
      - "ffmpeg:driveway_floodlight_cam#video=copy#audio=copy#audio=opus"

    driveway_floodlight_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h265Preview_01_sub

    backporch_cam:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main
      - "ffmpeg:backporch_cam#video=copy#audio=copy#audio=opus"

    backporch_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_sub


cameras:

  driveway_floodlight_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_cam_sub
          roles: ['detect']

        - path: rtsp://127.0.0.1:8554/driveway_floodlight_cam_sub
          roles: ['record']

    detect:
      enabled: True
      width: 1536
      height: 576
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - ups
        - amazon
        - fedex
        - package


  backporch_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backporch_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']

        - path: rtsp://127.0.0.1:8554/backporch_cam
          input_args: preset-rtsp-restream
          roles: ['record']



    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
      min_initialized: 2
      max_disappeared: 25
