logger:
  default: info

mqtt:
  host: emqx-listeners.default.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

# model:
#   path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr


ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30


go2rtc:
  streams:
    driveway_main:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main
      - "ffmpeg:driveway_floodlight_cam#video=copy#audio=copy#audio=opus"

    driveway_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_sub

    backporch_main:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main
      - "ffmpeg:backporch_cam#video=copy#audio=copy#audio=opus"

    backporch_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_sub


cameras:

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_main
          hwaccel_args: preset-intel-qsv-h265
          roles: ['record']

        - path: rtsp://127.0.0.1:8554/driveway_sub
          roles: ['detect']

    detect:
      enabled: True
      width: 1536
      height: 576
      fps: 10
    objects:
      track:
        - person
        - dog

    zones:
      # loitering_time: 3 # unit is in seconds
      front_yard:
        coordinates: 0.128,0.778,0.215,0.627,0.172,0.537,0.126,0.537,0.278,0.346,0.379,0.311,0.539,0.322,0.618,0.344,0.746,1,0.498,0.996,0.154,1,0.108,0.827,0.134,0.809
        objects:
          - person
          - dog
      front_porch:
        coordinates: 0.089,0.652,0.163,0.539,0.206,0.581,0.111,0.745
        objects:
          - person
      motion:
        mask:
          - 0.204,0.374,0.218,0.359,0.226,0.403,0.208,0.423

  backporch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backporch_main
          input_args: preset-rtsp-restream
          roles: ['record']

        - path: rtsp://127.0.0.1:8554/backporch_sub
          input_args: preset-rtsp-restream
          roles: ['detect']

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
