---
api:
  listen: :80
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 10.1.33.126:8555
    - stun:8555
  ice_servers:
    - urls:
       - stun:stun.cloudflare.com:3478
streams:
  backporch:
    - ffmpeg:rtsp://admin:{REOLINK_PASSWORd}@10.1.90.3/Preview_01_main
  driveway:
    - ffmpeg:rtsp://admin:{REOLINK_PASSWORd}@10.1.90.3/Preview_01_main