---
api:
  listen: :80
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 10.1.33.123:8555
    - stun:8555
  ice_servers:
    - urls:
       - stun:stun.cloudflare.com:3478
streams:
  backporch:
    - rtsp://admin:{REOLINK_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main
  driveway:
    - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main
