# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: ring-mqtt-configmap-secret
stringData:
  config.json: ENC[AES256_GCM,data:9d9SnR3cJOGr5tsvF0xP2Ow93jxQY0UwmdIAW5DD7KqYUysTh8lbThwWYnQ7cCnqZ9Ydv3s4gclEeRMJgc/74C0B3ng49ASwLpMUlSM8NxaYbLk8kQx/SCyht4EsndO762RUDg4/XmKvGOTBvg5IzUrKfVFzFtsWrbyjaDvH0eb2oQcOvF7aVu72Yus6+0yR8itPR20dUUTni4sKtIgNeiQ6wfVa8JIPN14QcZ4DquV1nAVGzALaLFrnFfaa1emRfrbGMgKXtj4fjDwd95mgu0aKN7pv0DlVOmZ2EMLPSP/Sau8dCTdZhjT0kWbnisvhsuzsPBeNkjtFTWCElJpuZ21xjauUJw9ypLToO4ilQntz5GyKhs81+CjtnJyM2FzOIt9DdIgPAkWnKomskxheZfD79MYI9tnoB5hhn2751Wjtlb+hSkGxBpFD/4vbtWyuKYT3Dqb5CkDL8SBFkuW8sg==,iv:dnGfPzfmtasdNcWRwt1wVqw1oipuTmn/ot+Lfohsi+0=,tag:JkxYYvc7EDHeALMEw2822w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jwm8ccjgfy04r9rwh65rehk72j6rkawkpjnf4rcu4ukwlcfyquhq4p2q23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS2lRaVovTWcwZTBGMkRw
        TXRhcG1SN01rYWRpZ20zTzVCQ1JPd3VJa1d3CnhqZGMyblQ0cGpqaGNyUStCR3BN
        SkMwa2xSS2pDcFk0M0tiRVVhQW9OYlUKLS0tIFNIRXF2cStjLyt0NzVtKzZSTk8x
        VGFEQzR6U29OVWptdjJIWlJCWDhGR1EKDDPqqiduzytzHwyHPIPUeDcCotkIyHg9
        H+ooES1+eRjEUqrnuNem+wyj36vKxtkT6Kdn3NOpVLbp57eP28tLRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-18T01:40:26Z"
  mac: ENC[AES256_GCM,data:QboGLwiHbEl9lO/rYqNVlhDrx46wcFXOgEJRIHCcKfSXAxp8arW3wftbUEXb0JFx3WIb4k96WwMFpKYKcSwesc0mikPpPExBxmY3vVXRXG3LJyxwrS0CEbAPKT3K64OQ5/i5N6os9TIYrHg02F2K/qTOzkPK0uQ0daU7TEjvKkc=,iv:c/jOdzZ5vClj3Cr9Nk4c5wxXeKZcr1aUvnmQQPKI7Dk=,tag:tbZVemn5ngG3xnxwHTbuHg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.0
