---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

rook-task-vars: &task-vars
  cluster: '{{.cluster | default "main"}}'
  node: "{{.node}}"
  ceph_disk: "{{.ceph_disk}}"
  ts: "{{.ts}}"
  jobName: "{{.jobName}}"

vars:
  waitForJobScript: ".taskfiles/Rook/scripts/wait-for-k8s-job.sh"
  ts: '{{now | date "150405"}}'

tasks:
  wipe-node-kube-01:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-01"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-01

  wipe-node-kube-02:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-02"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-02

  wipe-node-kube-03:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-03"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-03
  
  wipe-node-kube-04:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-04"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-04
  
  wipe-node-kube-05:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-05"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-05

  wipe-node-kube-06:
    desc: Trigger a wipe of Rook-Ceph data on node "kube-06"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/sda"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: kube-06

  wipe-disk:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-disk node=kube-01 ceph_disk="/dev/sda")
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDiskJobTemplate}}) | kubectl --context {{.cluster}} apply -f -
      - bash {{.waitForJobScript}} {{.wipeCephDiskJobName}} default {{.cluster}}
      - kubectl --context {{.cluster}} -n default wait job/{{.wipeCephDiskJobName}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} -n default logs job/{{.wipeCephDiskJobName}} --container list
      - kubectl --context {{.cluster}} -n default delete job {{.wipeCephDiskJobName}}
    vars:
      cluster: '{{.cluster | default "main"}}'
      node: '{{ or .node (fail "`node` is required") }}'
      ceph_disk: '{{ or .ceph_disk (fail "`ceph_disk` is required") }}'
      jobName: "wipe-disk-{{- .node -}}"
      wipeRookDiskJobTemplate: ".taskfiles/Rook/WipeDiskJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDiskJobTemplate}}

  wipe-data:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-data node=delta)
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDataJobTemplate}}) | kubectl --context {{.cluster}} apply -f -
      - bash {{.waitForJobScript}} {{.wipeRookDataJobName}} default {{.cluster}}
      - kubectl --context {{.cluster}} -n default wait job/{{.wipeRookDataJobName}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} -n default logs job/{{.wipeRookDataJobName}} --container list
      - kubectl --context {{.cluster}} -n default delete job {{.wipeRookDataJobName}}
    vars:
      cluster: '{{.cluster | default "main"}}'
      node: '{{ or .node (fail "`node` is required") }}'
      jobName: "wipe-rook-data-{{- .node -}}"
      wipeRookDataJobTemplate: ".taskfiles/Rook/WipeRookDataJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDataJobTemplate}}