---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@robsonhome.cloud
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: admin@robsonhome.cloud
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones: ["robsonhome.cloud"]
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@robsonhome.cloud
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: admin@robsonhome.cloud
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones: ["robsonhome.cloud"]