---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-technitium
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-technitium-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .TECHNITIUM_MAIN_RNDC_KEY }}"
  dataFrom:
    - extract:
        key: technitium