# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.robsonhome.cloud
        # - hdhomerun.robsonhome.cloud
        - pfs.robsonhome.cloud
        - pikvm.robsonhome.cloud
        # - receiver.robsonhome.cloud
        # - ups.robsonhome.cloud
        - vacuum.robsonhome.cloud
        # - zigbee-controller.robsonhome.cloud
        # - zwave-controller.robsonhome.cloud