---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./emby/ks.yaml
  - ./emqx/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./ring-mqtt/ks.yaml
  - ./unpackerr/ks.yaml
  - ./zigbee/ks.yaml
  - ./zwave/ks.yaml
