---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.js: |
          // Torrent content layout: Original
          // Default Torrent Management Mode: Automatic
          // Default Save Path: /media/downloads/torrents/complete
          // Incomplete Save Path: /media/downloads/torrents/incomplete

          module.exports = {
            action: "inject",
            apiKey: process.env.CROSS_SEED_API_KEY,
            delay: 30,
            duplicateCategories: true,
            flatLinking: true,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDir: "/media/downloads/torrents/complete/cross-seed",
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local:8080",
            skipRecheck: true,
            torrentDir: "/config/qBittorrent/BT_backup",
            torznab: [], // Only using annoucements from autobrr
          };
  dataFrom:
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: cross-seed