---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            delay: 30,
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local:8080",
            radarr: [
              "http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}",
            ],
            sonarr: [
              "http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}",
            ],
            torznab: [
              "http://prowlarr.default.svc.cluster.local/1/api?apikey={{ .PROWLARR_API_KEY }}",
              "http://prowlarr.default.svc.cluster.local/2/api?apikey={{ .PROWLARR_API_KEY }}",
              "http://prowlarr.default.svc.cluster.local/3/api?apikey={{ .PROWLARR_API_KEY }}",
            ],

            action: "inject",
            duplicateCategories: true,
            flatLinking: false,
            includeSingleEpisodes: false,
            includeNonVideos: false,
            matchMode: "safe",

            linkCategory: "cross-seed",
            linkType: "hardlink",
            linkDir: "/media/Downloads/qbittorrent/complete/cross-seed",

            outputDir: "/qbittorrent/xseeds",
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
          }
  dataFrom:
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: cross-seed