---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            port: 80,
            delay: 30,
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local:8080",

            sonarr: ["http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}"],
            radarr: ["http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}"],
            torznab: [
                4,
                12,
                14,
            ].map(i => `http://prowlarr.downloads.svc.cluster.local/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
            
            action: "inject",
            duplicateCategories: true,
            flatLinking: false,
            includeSingleEpisodes: true,
            includeNonVideos: false,
            matchMode: "safe",
            
            linkCategory: "cross-seed",
            linkType: "hardlink",
            linkDir: "/media/downloads/torrents/complete/cross-seed",

            outputDir: "/qbittorrent/xseeds",
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
          }
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr