---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cross-seed
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      cross-seed:
        annotations:
          confimap.reloader.stakater.com/reload: cross-seed-configmap
          secret.reloader.stakater.com/reload: cross-seed-secret
        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 5.9.2
            env:
              TZ: America/New_York
            args: ["daemon"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
    service:
      app:
        controller: cross-seed
        ports:
          http:
            port: 80
    persistence:
      config:
        type: emptyDir

      config-file:
        type: configMap
        name: cross-seed-configmap
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true


      qbittorrent:
        existingClaim: qbittorrent
        globalMounts:
          - path: /qbittorrent

      # media:
      #   type: nfs
      #   server: 10.1.10.210
      #   path: /mnt/tank/media
      #   globalMounts:
      #     - path: /media/downloads/qbittorrent
      #       subPath: downloads/qbittorrent