---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ring-mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ring-mqtt-secret
    creationPolicy: Owner
    template:
      data:
        # App
        MQTTHOST: "mqtt://{{ .X_EMQX_MQTT_USERNAME }}:{{ .X_EMQX_MQTT_PASSWORD }}@emqx-listeners.default.svc.cluster.local:1883"
        MQTTUSER: "{{ .X_EMQX_MQTT_USERNAME }}"
        MQTTPASSWORD: "{{ .X_EMQX_MQTT_PASSWORD }}"
        DISARMCODE: "{{ .RING_DISARM_CODE }}"
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: ring


