apiVersion: v1
kind: Secret
metadata:
  name: ring-mqtt-config-secret
stringData:
  config.yaml: ENC[AES256_GCM,data:K4DGjqiXGi+mgXe5uFa6/eSF7qXvLm1lF3laGd/tPbVbtk9Z5NW3vG9as0noacykp7D/Dk6ZCO4JPDiYQk2/MgCyLBJ0CLHWvvwdZQ5d7TixCkvI7jI0Hsf2OrMf3nNNLq/aZiuhz2GPoMYWJ83kfZkJdZSiFz9X5mzCAOV/6VDHBvk+EO94RUUd5O3C7adrrWDjMudjI2wyObPHrKOtnN/8S0dip7bXL1fERZG0sMQolmaEV7ShNBJJy8rw2/LoZKtbvXksXUh6JB5Q1nu+a7y4AjPWeIXr8SbxChhVZRRzTNdfYHu6Lqa1etabS4/9QNFXuSUayrDvGwiXyqo2k75bIF+2p18iM/6eOvFSaY5T3hPbUuXyMv8Vus3mkWJoFJfa3alNNhF8vMPfwd1zJXiZqSJlVVpyb3x8zT+KRvcOzVqxGUtp0q2Q/p+L3ygcRrBnfGRlct7HEiHpBUC+TiaLvz89Sw==,iv:S/BsE5ivHLXnfcrsIm/TCu6hDI5xsksZqYXnAhSX1To=,tag:KuKzYSTGm1slvkTYma0g3g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jwm8ccjgfy04r9rwh65rehk72j6rkawkpjnf4rcu4ukwlcfyquhq4p2q23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZ0hkcU5tVTA4emVoajhr
        TTRjeW53c3ZhT0Vnd0NIWU84YU8vdk0rc0c4CktVbXpmOFpvOFlObFRmUHo0NGlq
        ZzdQWmh1N0RBMWVra21XQlJGWkNvbW8KLS0tIHc5cnZVZ3pSdUlMUWwxN0tkU2Vq
        U04xQVcxU0RMa2FCQlErZ2hINXVtQWsK43Li8KN3DdhpCN2xY+5Q7pmDiPvWoMZ0
        YuTKUea/u6gcJEFsfiXGpX/hQklLgMejbHyYPrBKbpZA7797qa9cag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:52:04Z"
  mac: ENC[AES256_GCM,data:lfOxlVsslp4bisJKj56t3UhOivf5DplQ0YlW/uobg4Vw8TwIteK0H5XcoatTsHctYXfiW62fKP7+7Ee8SjV5LPUXwUPKBkziJ4lbI2QVD5X/8BGLKz9r4W5VbMQP9IFHVNiEBNGNS6ZJAscgKMdYUXRmhW6vT3u7Bqayj0iaGGE=,iv:BCrqEyhndrYhxqLFqVHVDUEUKZnvDLUwjeAOzSEhv4w=,tag:Wfb3vcYhTHKXpc0PGAGd+Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
