---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:

        # CROSS SEED
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"

        # # PROTONVPN
        WIREGUARD_ENDPOINT_IP: "{{ .WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"

        # PUSHOVER
        PUSHOVER_TOKEN: "{{ .QBITTORRENT_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"

  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: pushover
    - extract:
        key: gluetun
    - extract:
        key: qbittorrent
