---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # CROSS SEED
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"

        # # PROTONVPN
        # VPN_ENDPOINT_IP: "{{ .VPN_ENDPOINT_IP }}"
        # WIREGUARD_ADDRESS: "{{ .WIREGUARD_ADDRESS }}"
        # WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        # WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"

        
  dataFrom:
    - extract:
        key: cross-seed
    # - extract:
    #     key: gluetun
    
