---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 5.0.1@sha256:684422cab9fe3cba04812cf4207398bb72aa0f0283c92fddecd833648ac3f7bf
            env:
              TZ: America/New_York
              QBT_WEBUI_PORT: &port 80
              CROSS_SEED_ENABLED: false
              CROSS_SEED_HOST: cross-seed.default.svc.cluster.local
              CROSS_SEED_PORT: 80
              CROSS_SEED_SLEEP_INTERVAL: 0
              PUSHOVER_ENABLED: true
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
          gluetun:
              image:
                repository: ghcr.io/qdm12/gluetun
                tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
              env:
                VPN_SERVICE_PROVIDER: custom
                VPN_TYPE: wireguard
                VPN_INTERFACE: wg0
                WIREGUARD_ENDPOINT_PORT: 51820
                VPN_PORT_FORWARDING: on
                VPN_PORT_FORWARDING_PROVIDER: protonvpn
                FIREWALL_INPUT_PORTS: *port
                FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16, 10.43.0.0/16
              envFrom:
                - secretRef:
                    name: qbittorrent-secret
              securityContext:
                capabilities: { add: ["NET_ADMIN"] }
                allowPrivilegeEscalation: false
              resources:
                limits:
                  squat.ai/tun: "1"
          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.2@sha256:cb7d25d1a1249d326b9f1cf3afc1c6916b173e6784537245b07044420fd97372
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
      nodeSelector:
        topology.kubernetes.io/zone: w
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: ["sabnzbd"]
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 300
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.robsonhome.cloud
        className: internal
        hosts:
          - host: qb.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qbittorrent
      tmp:
        type: emptyDir
      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        globalMounts:
          - readOnly: true
      media:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media
        globalMounts:
          - path: /media/downloads/torrents
            subPath: downloads/torrents
