---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      qbittorrent:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-scripts,qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret
          # reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: false
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 0
              - 10000
              - 65542 # External-services Truenas
            seccompProfile: { type: RuntimeDefault }
          nodeSelector:
            topology.kubernetes.io/zone: w
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values: ["sabnzbd"]
                    topologyKey: kubernetes.io/hostname
          terminationGracePeriodSeconds: 300

        initContainers:
            dnsdist:
              image:
                repository: docker.io/powerdns/dnsdist-19
                tag: 1.9.7
              restartPolicy: Always

            gluetun:
              dependsOn:
                - dnsdist

              image:
                repository: ghcr.io/qdm12/gluetun
                tag: v3.35.0
              env:
                DOT: "off"
                DNS_ADDRESS: "127.0.0.2"
                VPN_SERVICE_PROVIDER: custom
                VPN_TYPE: wireguard
                VPN_INTERFACE: wg0
                WIREGUARD_ENDPOINT_PORT: 51820
                VPN_PORT_FORWARDING: on
                VPN_PORT_FORWARDING_PROVIDER: protonvpn
                FIREWALL_INPUT_PORTS: 80
                FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/12,10.43.0.0/16 # Allow access to k8s subnets
              envFrom:
                - secretRef:
                    name: qbittorrent-secret
              resources:
                limits:
                  squat.ai/tun: "1"
              restartPolicy: Always
              securityContext:
                capabilities:
                  add:
                    - NET_ADMIN
                    - NET
                allowPrivilegeEscalation: false

        containers:
            app:
              nameOverride: qbittorrent
              image:
                repository: ghcr.io/onedr0p/qbittorrent-beta
                tag: 5.0.1@sha256:684422cab9fe3cba04812cf4207398bb72aa0f0283c92fddecd833648ac3f7bf
              env:
                TZ: America/New_York
                QBT_WEBUI_PORT: &port 80
                CROSS_SEED_ENABLED: false
                CROSS_SEED_HOST: cross-seed.default.svc.cluster.local
                CROSS_SEED_PORT: 80
                CROSS_SEED_SLEEP_INTERVAL: 0
                PUSHOVER_ENABLED: true
              envFrom:
                - secretRef:
                    name: qbittorrent-secret
              probes:
                liveness:
                  enabled: true
                readiness:
                  enabled: true
                startup:
                  enabled: true
                  spec:
                    failureThreshold: 30
                    periodSeconds: 10
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
              resources:
                requests:
                  cpu: 150m
                  memory: 2048Mi
                limits:
                  memory: 8192Mi

            port-forward:
              image:
                repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
                tag: 0.0.2@sha256:3b97aaa6ff52037a4f9150ea3bb27ff949a1e1afd1044dcff0db3e9e56f807e4
              env:
                GLUETUN_CONTROL_SERVER_HOST: localhost
                GLUETUN_CONTROL_SERVER_PORT: 8000
                QBITTORRENT_HOST: localhost
                QBITTORRENT_WEBUI_PORT: *port
                CRON_ENABLED: true
                CRON_SCHEDULE: "*/5 * * * *"
                LOG_TIMESTAMP: false
              securityContext:
                runAsUser: 568
                runAsGroup: 568
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.robsonhome.cloud
        className: internal
        hosts:
          - host: qb.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qbittorrent
        advancedMounts:
          qbittorrent:
            app:
              - path: /config

      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config


      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        globalMounts:
          - readOnly: true

      dnsdist:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          qbittorrent:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true

      media:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media
        globalMounts:
          - path: /media/downloads/torrents
            subPath: downloads/torrents
