---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    controllers:
      qbittorrent:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            nameOverride: *app
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3@sha256:025f32d260a3e924885405c0ca01ab8e396360330438ef8562ffd973d2dbb927
            env:
              UMASK: "022"
              TZ: America/New_York
              QBITTORRENT__PORT: &port 80
              CROSS_SEED_ENABLED: false
              CROSS_SEED_HOST: cross-seed.default.svc.cluster.local
              CROSS_SEED_PORT: 80
              CROSS_SEED_SLEEP_INTERVAL: 0
              PUSHOVER_ENABLED: true
              CROSS_SEED_API_KEY:
               valueFrom:
                  secretKeyRef:
                   name: qbittorrent-secret
                   key: CROSS_SEED_API_KEY
              PUSHOVER_TOKEN:
               valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: PUSHOVER_TOKEN
              PUSHOVER_USER_KEY:
               valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: PUSHOVER_USER_KEY
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__RootFolder: /add-ons/VueTorrent
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
                memory: 1G
              limits:
                memory: 12G

          vuetorrent:
            dependsOn: *app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.0
            args:
              - --repo=https://github.com/VueTorrent/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/add-ons
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
              limits:
                memory: 50Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups:
                - 65534

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
            env:
              # DOT: "off"
              # DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 80
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16
              WIREGUARD_ENDPOINT_IP:
               valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: WIREGUARD_ENDPOINT_IP
              WIREGUARD_ADDRESSES:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: WIREGUARD_ADDRESSES
              WIREGUARD_PRIVATE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: WIREGUARD_PRIVATE_KEY
              WIREGUARD_PUBLIC_KEY:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: WIREGUARD_PUBLIC_KEY
            resources:
              limits:
                squat.ai/tun: "1"
            securityContext:
              capabilities: { add: ["NET_ADMIN"] }
              allowPrivilegeEscalation: false

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.2@sha256:14b9a10cda0a8dff6bd2d131686d3f6b8dd550a4a835674b22aaa711b4c34ecd
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: qb.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent

      add-ons:
        type: emptyDir
        globalMounts:
          - path: /add-ons

      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        globalMounts:
          - readOnly: true

      media:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/media
        globalMounts:
          - path: /media/downloads/torrents
            subPath: downloads/torrents
