---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      annotations:
          k8s.v1.cni.cncf.io/networks: |
            [{
              "name":"netattach-iot",
              "namespace": "network",
              "ips": ["10.1.40.203/24"],
              "mac": "3e:59:e4:f7:43:09"
            }]
      nodeSelector:
          google.feature.node.kubernetes.io/coral: 'true'
          intel.feature.node.kubernetes.io/gpu: 'true'
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 109
          - 65542 # gladius:external-services
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.138.7-noble-full
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
                gpu.intel.com/i915: '1'
              limits:
                gpu.intel.com/i915: '1'
                memory: 2Gi

    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136

    ingress:
      app:
        className: internal
        hosts:
          - host: scrypted.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: scrypted
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      recs:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/scrypted
        globalMounts:
          - path: /recs
