---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations: {}
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
            fsGroup: 3000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/scrypted
              tag: 0.139.0@sha256:0a376e9166d51e0d0fae47b9234774338809fdbd317db614fdc95cef532f024e
            env:
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 500m
                memory: 128Mi
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 8192Mi

    service:
      app:
        ports:
          http:
            port: &port 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136
    route:
      app:
        hostnames:
          - scrypted.robsonhome.cloud
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config

      tmpfs:
        type: emptyDir
        advancedMounts:
          scrypted:
            app:
              - path: /.cache
                subPath: cache
              - path: /.npm
                subPath: npm-cache
      recs:
        type: nfs
        server: truenas.internal
        path: /mnt/tank/scrypted
        globalMounts:
          - path: /recordings


