---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: technitium-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      # https://github.com/kubernetes-sigs/external-dns/pull/5226
      repository: gcr.io/k8s-staging-external-dns/external-dns
      tag: v20250402-v0.16.1-48-g1efdf416
    provider:
      name: pihole
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pihole-dns-secret
            key: *name
    extraArgs:
      - --ignore-ingress-tls-spec
      - --pihole-server=https://10.1.20.43
      - --pihole-tls-skip-verify
      - --pihole-api-version=6
    triggerLoopOnEvent: true
    policy: upsert-only
    registry: noop
    sources: ["gateway-httproute", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters: ["robsonhome.cloud"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
