---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pihole-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  install:
    remediation:
      retries: -1
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: https://10.1.20.44
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pihole-dns-secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    policy: upsert-only
    sources: ["gateway-httproute", "service"]
    registry: noop
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
