---
originRequest:
  originServerName: external.robsonhome.cloud

ingress:
  - hostname: robsonhome.cloud
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.robsonhome.cloud"
    service: *svc
  - service: http_status:404