---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas.robsonhome.cloud
        # - garage-door.robsonhome.cloud
        # - hdhomerun.robsonhome.cloud
        # - idrac.robsonhome.cloud
        # - kiosk.robsonhome.cloud
        # - kvm.robsonhome.cloud
        - pikvm.robsonhome.cloud
        # - receiver.robsonhome.cloud
        # - ups.robsonhome.cloud
        # - vacuum.robsonhome.cloud
        - zigbee-controller.robsonhome.cloud
        - zwave-controller.robsonhome.cloud
