apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:wQbbHZ3+53Yt/yms+K/YODfTs4RqOgn6cEAroQQHUzliBSbrsX068v5b/BZY7bFzp8poTFpHo2X1KbiFIBC3YkYTnausDMX6Ts8=,iv:y50rKYt19lmH574171DW4smbxsfC8taeee9wFLODlbs=,tag:q2raJu7QVVE00700U7dxBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jwm8ccjgfy04r9rwh65rehk72j6rkawkpjnf4rcu4ukwlcfyquhq4p2q23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQXU5NjlmTjNjS3RRZkhv
        UmxqRHJwMmhEb2J6aVBvZHRmWkUwWW9RV1dNCndkb2Yva1VlbVBVMGZ0WTIwWHFz
        LzlKeFBMbnZoVC94czJESUZUWGd6MTAKLS0tIGpIOEtMMWV6NThFaFhSTnNyZ0hi
        N1NjUjVVajJQYnlva1NNK1NldmRITWcKqywfG+e/28aWlf+Geh6kuipb75pLB9fR
        dC0vH5l4aTxyjAeZ7xE+JitMxlejjmYBS9UMZaWMsUU8welUAMRNXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-22T20:58:28Z"
  mac: ENC[AES256_GCM,data:O+mMpa6WmbQqBaDwoAwQKvclmrzhKBIpBHILFt6VZV+6tzemDWtMvbP4gR8SBHE5TuiSd4Lu7saL197NJtB2zZSrqE044W265Mi7sO3b1Bf/toFixp/XV94zcWP0gfMhSeiaPvkaRwLKhYvHSN3Jv5Q+GOl1FqI13hbuj+QM4fw=,iv:XVPc00/u/Mzg+fCfR5R5EigbWBgakOmq0luD6HEXGmE=,tag:ZYBEiX5YWWrsYNYd++RCEQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
