---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      nodeSelector:
          google.feature.node.kubernetes.io/coral: 'true'
          intel.feature.node.kubernetes.io/gpu: 'true'
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.122.0-jammy-full
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 136m
                memory: 1024Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 8192Mi
            securityContext:
              privileged: true
    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
            primary: true
          rebroadcast:
            port: 34135

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.robsonhome.cloud
        hosts:
          - host: scrypted.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: scrypted
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      dev-bus-usb:
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
      sys-bus-usb:
        type: hostPath
        hostPath: /sys/bus/usb
        hostPathType: Directory
      recs:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/apps/scrypted
        globalMounts:
          - path: /recordings