---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-opnsense
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-opnsense-secret
    template:
      data:
        OPNSENSE_API_KEY: "{{ .OPNSENSE_API_KEY }}"
        OPNSENSE_API_SECRET: "{{ .OPNSENSE_API_SECRET }}"
  dataFrom:
    - extract:
        key: opnsense
