---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      zwave:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 11.2.1@sha256:7fc0a78a6c843654eb93166decd13192b5a1f53637cf117ea13569f2a33a0e94
            env:
              TZ: America/New_York
              PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                squat.ai/zwave: '1'
                cpu: 10m
              limits:
                squat.ai/zwave: '1'
                memory: 512Mi
    # defaultPodOptions:
      # nodeSelector:
      #   homeseer.feature.node.kubernetes.io/zwave: "true" # NFD label for zwave usb
    service:
      app:
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.robsonhome.cloud"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        existingClaim: zwave
        globalMounts:
          - path: /usr/src/app/store
      config-cache:
        existingClaim: zwave-cache
        globalMounts:
          - path: /usr/src/app/store/.config-db
      tmp:
        type: emptyDir
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E9045056-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E9045056-if00
