---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opnsense-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.1
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: opnsense-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # https://artifacthub.io/packages/helm/external-dns/external-dns?modal=values
    fullnameOverride: external-dns-opnsense
    logLevel: info
    interval: 2m
    provider:
      name: webhook
      managedRecordTypes:
        - A
        - AAAA
      webhook:
        image:
          repository: ghcr.io/jobs62/opnsense_unbound_external-dns_webhook
          tag: v0.4.5@sha256:22d3bd25bacaa0a8445a746d6541a8994bcb54e6047f5a079574adc792f88034
        env:
          - name: OPNSENSE_SECRET
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-opnsense-credentials
                key: OPNSENSE_API_SECRET
          - name: OPNSENSE_KEY
            valueFrom:
              secretKeyRef:
                name: *secret
                key: OPNSENSE_API_KEY
          - name: OPNSENSE_BASE
            value: http://opnsense.robsonhome.cloud
          - name: OPNSENSE_ALLOW_INVALID_CERTS
            value: "false"
          - name: OPNSENSE_DOMAIN_FILTERS
            value: '[".robsonhome.cloud"]'
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ignore-ingress-tls-spec
      - --annotation-filter=external-dns/opnsense in (true)
      - --webhook-provider-url=http://localhost:8800
    policy: sync
    sources:
      - ingress
      - service
      - crd
    registry: noop
    domainFilters:
      - robsonhome.cloud
    txtOwnerId: default
    txtPrefix: k8s.
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret