---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [10000]
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: version-v7.4.0@sha256:fe57cc3a6d3ec8937c07d3230497577782c549f80f490897649f9b9650426fb3
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 15m
                memory: 324M
              limits:
                memory: 604M
    service:
      app:
        enabled: true
        controller: app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local:/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.robsonhome.cloud?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
          # hajimari.io/enable: "true"
          # hajimari.io/icon: bookshelf
        hosts:
          - host: &host calibre.robsonhome.cloud
            paths:
              - path: /
                service:
                  name: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: calibre
        globalMounts:
          - path: /config
      books:
        enabled: true
        type: nfs
        server: 10.1.30.210
        path: /mnt/tank/media
        globalMounts:
          - path: /data/media
