---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  apply-ks:
    desc: Apply a Flux Kustomization resource for a cluster
    summary: |
      cluster: Cluster to run command against (required)
      path: Path to the Flux Kustomization resource (required)
      ns: Namespace the Flux Kustomization exists in (default: flux-system)
    cmd: |
      flux --context {{.cluster}} build ks $(basename {{.path}}) \
          --namespace {{.ns}} \
          --kustomization-file {{.KUBERNETES_DIR}}/{{.cluster}}/apps/{{.path}}/ks.yaml \
          --path {{.KUBERNETES_DIR}}/{{.cluster}}/apps/{{.path}} \
          {{- if contains "not found" .ks }}--dry-run \{{ end }}
      | \
      kubectl --context {{.cluster}} apply --server-side \
          --field-manager=kustomize-controller -f -
    requires:
      vars: ["cluster", "path"]
    vars:
      ns: '{{.ns | default "flux-system"}}'
      ks:
        sh: flux --context {{.cluster}} --namespace {{.ns}} get kustomizations $(basename {{.path}}) 2>&1
    preconditions:
      - test -f {{.KUBERNETES_DIR}}/{{.cluster}}/apps/{{.path}}/ks.yaml
  delete-failed-pods:
    desc: Deletes pods with Failed phase
    summary: |
      Args:
        cluster: Cluster to run command against (default: main)
    vars:
      cluster: '{{.cluster | default "main"}}'
    cmds:
      - kubectl --context {{.cluster}} delete pods --field-selector status.phase=Failed -A --ignore-not-found=true

  delete-succeeded-pods:
    desc: Deletes pods with Succeeded phase
    summary: |
      Args:
        cluster: Cluster to run command against (default: main)
    vars:
      cluster: '{{.cluster | default "main"}}'
    cmds:
      - kubectl --context {{.cluster}} delete pods --field-selector status.phase=Succeeded -A --ignore-not-found=true

  delete-pending-pods:
    desc: Deletes pods with Pending phase
    summary: |
      Args:
        cluster: Cluster to run command against (default: main)
    vars:
      cluster: '{{.cluster | default "main"}}'
    cmds:
      - kubectl --context {{.cluster}} delete pods --field-selector status.phase=Pending -A --ignore-not-found=true
  
  browse-pvc:
    desc: Browse a PersistentVolumeClaim
    summary: |
      cluster: Cluster to run command against (default: main)
      ns: Namespace to browse PersistentVolumeClaims in (default: default)
      claim: PersistentVolumeClaim to browse (required)
    interactive: true
    cmd: kubectl browse-pvc --context {{.cluster}} --namespace {{.ns}} {{.claim}}
    vars:
      cluster: '{{.cluster | default "main"}}'
      ns: '{{.ns | default "default"}}'
    requires:
      vars: ["claim"]
    preconditions:
      - kubectl --context {{.cluster}} --namespace {{.ns}} get persistentvolumeclaims {{.claim}}

  sync-secrets:
    desc: Sync ExternalSecret resources from provider
    summary: |
      cluster: Cluster to run command against (default: main)
      ns: Namespace to sync secret in (default: default)
      secret: Secret to sync (default: unset/all secrets)
    cmd: |
      {{if eq .secret ""}}
        kubectl get externalsecret --all-namespaces --no-headers -A | awk '{print $1, $2}' \
          | xargs --max-procs=2 -l bash -c 'kubectl -n $0 annotate externalsecret $1 force-sync=$(date +%s) --overwrite'
      {{else}}
        kubectl --context {{.cluster}} --namespace {{.ns}} annotate externalsecret {{.secret}} force-sync=$(date +%s) --overwrite
      {{end}}
    vars:
      secret: '{{ .secret | default ""}}'
      ns: '{{.ns | default "default"}}'
      cluster: '{{.cluster | default "main"}}'
    preconditions:
      - kubectl --context {{.cluster}} --namespace {{.ns}} get externalsecret {{.secret}}