---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: frigate-secret
    template:
      data:
        PLUS_API_KEY: "{{ .FRIGATE_PLUS_API_KEY }}"
        FRIGATE_CAMERA_USER: "{{ .REOLINK_USERNAME }}"
        FRIGATE_CAMERA_PASSWORD: "{{ .REOLINK_PASSWORD }}"
  dataFrom:
    - extract:
        key: frigate
    - extract:
        key: reolink
