---
originRequest:
  originServerName: external.robsonhome.cloud

ingress:
  - hostname: robsonhome.cloud
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.robsonhome.cloud"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
