logger:
  default: info

mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

model:
  path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
  width: 320
  height: 320
  input_pixel_format: rgb

detectors:
  coral:
    type: edgetpu
    device: pci

objects:
  track: ['person', 'dog', 'face', 'cat', 'amazon', 'ups', 'fedex']
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-vaapi
  output_args: 
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects

go2rtc:
  streams:
    reolink_backporch_turret_cam_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main#video=h264#audio=copy#audio=opus#hardware"
      # - ffmpeg:reolink_backporch_turret_cam#video=copy#audio=aac#audio=opus#hardware
    reolink_backporch_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_sub

    reolink_floodlight_cam_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main#video=h264#audio=copy#audio=opus#hardware"
    reolink_floodlight_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_sub
    

cameras:
  reolink_floodlight_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_floodlight_cam_main
          input_args: preset-rtsp-restream
          roles: ['record']
          
        - path: rtsp://127.0.0.1:8554/reolink_floodlight_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 7

        
    motion:
      mask: 1133,204,1349,266,1451,311,1536,576,1094,576,931,163
    zones:
      driveway:
        coordinates: 798,413,830,180,582,172,339,358,193,440,279,576,773,576
      front_porch:
        coordinates: 290,328,355,285,436,300,266,412,194,467,134,379,256,317
      front_yard:
        coordinates: 497,178,828,201,766,576,1073,576,1031,436,976,301,946,279,917,231,925,195,921,157,849,150,762,144,646,140,561,127,506,131,436,167,224,282,354,265

  reolink_backporch_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_backporch_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']


        - path: rtsp://127.0.0.1:8554/reolink_backporch_cam_main
          input_args: preset-rtsp-restream
          roles: ['record']

    motion:
      mask: 418,176,141,181,106,89,71,0,169,0,332,0,640,0,640,248
    zones:
      back_porch:
        coordinates: 640,256,568,172,407,199,255,200,241,235,131,235,94,271,40,480,640,480

  