logger:
  default: info

mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

# model:
#   path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr


ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning", "-threads", "2"]
  hwaccel_args: preset-vaapi

# objects:
#   track:
#     - person
#     - face
#     - license_plate
#     - dog
#     - cat
#     - car
#     - amazon
#     - fedex
#     - ups
#     - package

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  crop: true
  retain:
    default: 20
    objects:
      person: 30


record:
  enabled: true
  retain:
    mode: all
  events:
    pre_capture: 2
    retain:
      default: 20
      mode: all

go2rtc:
  streams:
    driveway_floodlight_cam:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main#video=h264#audio=copy#audio=opus#hardware"

    driveway_floodlight_cam_sub:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus"

    backporch_cam:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_mainh264Preview_01_main#video=h264#audio=copy#audio=opus#hardware"

    backporch_cam_sub:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus"

cameras:
  driveway_floodlight_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_cam
          input_args: preset-rtsp-restream
          roles: ['record']

        - path: rtsp://127.0.0.1:8554/driveway_floodlight_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']

    detect:
      enabled: True
      width: 1536
      height: 576
      fps: 7

    objects:
      track:
        - person
        - dog
        - cat
        - package
        - cat

    motion:
      mask: "0.732,1,0.603,0.195,0.851,0.397,0.955,0.501,1,0.218,0.997,0.992"

    zones:
      front_yard:
        coordinates: 0.086,0.675,0.066,0.59,0.119,0.506,0.153,0.473,0.219,0.382,0.285,0.309,0.317,0.288,0.373,0.296,0.535,0.325,0.629,0.353,0.728,0.992,0.156,0.995,0.119,0.836,0.134,0.813
        inertia: 3
        objects:
          - person
          - dog
          - cat
          - package


  backporch_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backporch_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: ['record']
        - path: rtsp://127.0.0.1:8554/backporch_cam_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: ['detect']


    objects:
      track:
        - person
        - dog
        - cat

    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5

    zones:
     back_porch:
      coordinates: 0.662,0.362,0.711,0.999,0.042,1,0.194,0.385
      inertia: 3
      objects:
          - person
          - dog
          - cat


