logger:
  default: info

mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

model:
  path: plus://05fafebf939bb56823f402e6cf2f3d0f #EdgeTPU Model
  width: 320
  height: 320
  input_pixel_format: rgb

detectors:
  coral:
    type: edgetpu
    device: pci

objects:
  track: ['person', 'dog', 'face', 'cat', 'amazon', 'ups', 'fedex']
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-vaapi
  output_args: 
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 1

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    retain:
      default: 1
      mode: active_objects

go2rtc:
  streams:
    reolink_backporch_turret_cam_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_main#video=copy#audio=copy#audio=opus#hardware"
      # - ffmpeg:reolink_backporch_turret_cam#video=copy#audio=aac#audio=opus#hardware
    reolink_backporch_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.3:554/h264Preview_01_sub

    reolink_floodlight_cam_main:
      - "ffmpeg:rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_main#video=copy#audio=copy#audio=opus#hardware"
    reolink_floodlight_cam_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@10.1.90.4:554/h264Preview_01_sub
    

cameras:
  reolink_floodlight_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_floodlight_cam_main
          input_args: preset-rtsp-restream
          roles: ['record']
          
        - path: rtsp://127.0.0.1:8554/reolink_floodlight_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 7

        
    motion:
      mask: 1133,204,1349,266,1451,311,1536,576,1094,576,931,163
    zones:
      driveway:
        coordinates: 0.126,0.767,0.23,0.602,0.384,0.259,0.419,0.251,0.495,0.246,0.556,0.263,0.54,0.277,0.503,1,0.183,0.999
      front_porch:
        coordinates: 0.096,0.664,0.091,0.626,0.084,0.632,0.074,0.592,0.117,0.532,0.13,0.596,0.156,0.558,0.17,0.552,0.188,0.573,0.231,0.493,0.275,0.517,0.215,0.632,0.205,0.596,0.117,0.739
      front_yard_left:
        coordinates: 0.196,0.442,0.253,0.361,0.29,0.3,0.337,0.278,0.268,0.4,0.236,0.487,0.195,0.558,0.183,0.495
      front_yard_right:
        coordinates: 0.554,0.266,0.54,0.287,0.526,0.574,0.504,1,0.703,1,0.65,0.589,0.605,0.282
      

  reolink_backporch_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_backporch_cam_sub
          input_args: preset-rtsp-restream
          roles: ['detect']


        - path: rtsp://127.0.0.1:8554/reolink_backporch_cam_main
          input_args: preset-rtsp-restream
          roles: ['record']

    motion:
      mask: 418,176,141,181,106,89,71,0,169,0,332,0,640,0,640,248
    zones:
      back_porch:
        coordinates: 640,256,568,172,407,199,255,200,241,235,131,235,94,271,40,480,640,480

  