---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizationresources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: generic-device-plugin-configmap
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
